/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type DifficultyLevel = 0 | 1 | 2;

export const DifficultyLevel = {
    NUMBER_0: 0 as DifficultyLevel,
    NUMBER_1: 1 as DifficultyLevel,
    NUMBER_2: 2 as DifficultyLevel
};
