// <auto-generated />

using EP.Balda.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EP.Balda.Data.Migrations.PlayerDbMigrations
{
    [DbContext(typeof(PlayerDbContext))]
    internal class PlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EP.Balda.Data.Models.PlayerDb", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Login");

                b.Property<string>("NickName");

                b.Property<string>("Password");

                b.Property<int>("Score");

                b.HasKey("Id");

                b.ToTable("Players");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Login = "Daisha.Upton",
                        NickName = "Tonya.Bauch",
                        Password = "BILs4",
                        Score = 85
                    },
                    new
                    {
                        Id = 3,
                        Login = "Troy71",
                        NickName = "Taylor41",
                        Password = "7wlhc",
                        Score = 73
                    },
                    new
                    {
                        Id = 5,
                        Login = "Linda.Crona99",
                        NickName = "Samantha_Tromp",
                        Password = "e7HW4",
                        Score = 99
                    },
                    new
                    {
                        Id = 7,
                        Login = "Alvera76",
                        NickName = "Gilbert.Toy",
                        Password = "OvRL1",
                        Score = 44
                    },
                    new
                    {
                        Id = 9,
                        Login = "Elian.Greenholt",
                        NickName = "Woodrow21",
                        Password = "mwY2N",
                        Score = 53
                    },
                    new
                    {
                        Id = 11,
                        Login = "Ruthe87",
                        NickName = "Margie_Weissnat15",
                        Password = "SiRgM",
                        Score = 20
                    },
                    new
                    {
                        Id = 13,
                        Login = "Urban_Lind27",
                        NickName = "Morris_Hettinger",
                        Password = "2VwoR",
                        Score = 23
                    },
                    new
                    {
                        Id = 15,
                        Login = "Dayna.MacGyver",
                        NickName = "Erin.Goyette",
                        Password = "avwDB",
                        Score = 13
                    },
                    new
                    {
                        Id = 17,
                        Login = "Rowena_Walker",
                        NickName = "Sonya.Block50",
                        Password = "SvYvV",
                        Score = 78
                    },
                    new
                    {
                        Id = 19,
                        Login = "Stewart_Macejkovic60",
                        NickName = "Viola73",
                        Password = "Qy9Xy",
                        Score = 59
                    });
            });
#pragma warning restore 612, 618
        }
    }
}