// <auto-generated />
using System;
using EP.TicTacToe.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EP.TicTacToe.Data.Migrations.GameDbMigrations
{
    [DbContext(typeof(TicTacDbContext))]
    [Migration("20190711213204_InitialCreateDb")]
    partial class InitialCreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EP.TicTacToe.Data.Models.CellDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MapId");

                    b.Property<int>("TicTac");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.FirstPlayerDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HaunterId");

                    b.Property<int>("TicTac");

                    b.HasKey("Id");

                    b.HasIndex("HaunterId");

                    b.ToTable("FirstPlayers");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.GameDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.HaunterDb", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Haunters");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.MapDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<int>("Size");

                    b.Property<int>("WinningChain");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.PlayerDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FirstPlayerId");

                    b.Property<int?>("GameId");

                    b.Property<int?>("SecondPlayerId");

                    b.HasKey("Id");

                    b.HasIndex("FirstPlayerId")
                        .IsUnique();

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("SecondPlayerId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.SecondPlayerDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HaunterId");

                    b.Property<int>("TicTac");

                    b.HasKey("Id");

                    b.HasIndex("HaunterId");

                    b.ToTable("SecondPlayers");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.StepResultDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<int>("NextPlayerId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("StepResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.CellDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.MapDb", "Map")
                        .WithMany("Cells")
                        .HasForeignKey("MapId");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.FirstPlayerDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.HaunterDb", "Haunter")
                        .WithMany("FirstPlayers")
                        .HasForeignKey("HaunterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.MapDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.GameDb", "Game")
                        .WithOne("Map")
                        .HasForeignKey("EP.TicTacToe.Data.Models.MapDb", "GameId");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.PlayerDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.FirstPlayerDb", "FirstPlayer")
                        .WithOne("Player")
                        .HasForeignKey("EP.TicTacToe.Data.Models.PlayerDb", "FirstPlayerId");

                    b.HasOne("EP.TicTacToe.Data.Models.GameDb", "Game")
                        .WithOne("Player")
                        .HasForeignKey("EP.TicTacToe.Data.Models.PlayerDb", "GameId");

                    b.HasOne("EP.TicTacToe.Data.Models.SecondPlayerDb", "SecondPlayer")
                        .WithOne("Player")
                        .HasForeignKey("EP.TicTacToe.Data.Models.PlayerDb", "SecondPlayerId");
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.SecondPlayerDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.HaunterDb", "Haunter")
                        .WithMany("SecondPlayers")
                        .HasForeignKey("HaunterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EP.TicTacToe.Data.Models.StepResultDb", b =>
                {
                    b.HasOne("EP.TicTacToe.Data.Models.GameDb", "Game")
                        .WithMany("StepResults")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
