// <auto-generated />
using System;
using EP.SeaBattle.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EP.SeaBattle.Data.Migrations
{
    [DbContext(typeof(SeaBattleDbContext))]
    [Migration("20190612080419_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EP.SeaBattle.Data.Models.CellDb", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShipDbId");

                    b.Property<int>("Status");

                    b.Property<byte>("X");

                    b.Property<byte>("Y");

                    b.HasKey("Id");

                    b.HasIndex("ShipDbId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.GameDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Finish");

                    b.Property<string>("Player1Id");

                    b.Property<string>("Player2Id");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.PlayerDb", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CanShoot");

                    b.Property<string>("NickName");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.ShipDb", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GameId");

                    b.Property<string>("PlayerId");

                    b.Property<int>("Rank");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.CellDb", b =>
                {
                    b.HasOne("EP.SeaBattle.Data.Models.ShipDb")
                        .WithMany("Cells")
                        .HasForeignKey("ShipDbId");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.GameDb", b =>
                {
                    b.HasOne("EP.SeaBattle.Data.Models.PlayerDb", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("EP.SeaBattle.Data.Models.PlayerDb", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");
                });

            modelBuilder.Entity("EP.SeaBattle.Data.Models.ShipDb", b =>
                {
                    b.HasOne("EP.SeaBattle.Data.Models.GameDb", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("EP.SeaBattle.Data.Models.PlayerDb", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
